version: "3.8"

services:

  nginx:
    image: nginx:1.21
    ports: [ 8000 ]
    volumes:
      - "./nginx/app.conf:/etc/nginx/conf.d/app.conf:ro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    networks: [ blue, green ]

  app-green:
    image: bgapp:${VERSION:-latest}
    ports: [ 8000 ]
    environment:
      - "VERSION=${VERSION:-latest}"
      - "COLOR=green"
    networks: [ green ]

  app-blue:
    image: bgapp:${VERSION:-latest}
    ports: [ 8000 ]
    environment:
      - "VERSION=${VERSION:-latest}"
      - "COLOR=blue"
    depends_on: [ nginx ]
    networks: [ blue ]


networks:
  default:
  green:
  blue:
