apiVersion: v1
kind: Service
metadata:
  name: bgapp
  labels:
    app: bgapp
    role: ${ROLE}
    env: dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: bgapp
    role: ${ROLE}
